/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package minecraft.client.GUI;

import com.jtattoo.plaf.hifi.HiFiLookAndFeel;

import minecraft.client.GUI.Background.VersionsVanilla;
import minecraft.client.util.ColorUtils;

import javax.swing.BorderFactory;

import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.border.Border;
import minecraft.client.GUI.Background.VersionsFabric;
import minecraft.client.GUI.Background.VersionsForge;

/**
 *
 * @author keiner5212
 */
public class Main extends javax.swing.JFrame {

    public Main() {

        try {
            // look and feel
            UIManager.setLookAndFeel(new HiFiLookAndFeel());

            // logo
            ImageIcon icono = new ImageIcon(getClass().getResource("/logo.png"));
            setIconImage(icono.getImage());

            // title
            setTitle("Minecraft Launcher (By keiner5212)");

        } catch (Exception e) {
            e.printStackTrace();
        }

        initComponents();

        // config
        setLocationRelativeTo(null);
        setResizable(true);
        loaderversionlabel.setVisible(false);
        loaderversion.setVisible(false);

        Border rightBorder = BorderFactory.createMatteBorder(0, 0, 0, 2, ColorUtils.hexStringToColor("#111"));
        instalations_and_name.setBorder(rightBorder);

        Border topBorder = BorderFactory.createMatteBorder(2, 0, 0, 0, ColorUtils.hexStringToColor("#111"));
        play_download.setBorder(topBorder);

        VersionsVanilla versionsThread = new VersionsVanilla(versions, typeFilter.getSelectedItem().toString());
        Thread thread = new Thread(versionsThread);
        thread.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        instalations_and_name = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        play_download = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        versions = new javax.swing.JComboBox<>();
        loaderlabel = new javax.swing.JLabel();
        Loader = new javax.swing.JComboBox<>();
        typelabel = new javax.swing.JLabel();
        typeFilter = new javax.swing.JComboBox<>();
        loaderversionlabel = new javax.swing.JLabel();
        loaderversion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        instalations_and_name.setMaximumSize(new java.awt.Dimension(300, 32767));
        instalations_and_name.setMinimumSize(new java.awt.Dimension(300, 0));

        javax.swing.GroupLayout instalations_and_nameLayout = new javax.swing.GroupLayout(instalations_and_name);
        instalations_and_name.setLayout(instalations_and_nameLayout);
        instalations_and_nameLayout.setHorizontalGroup(
            instalations_and_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        instalations_and_nameLayout.setVerticalGroup(
            instalations_and_nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(instalations_and_name);

        jLabel1.setText("Select the game version:");

        versions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loading" }));

        loaderlabel.setText("Select loader:");

        Loader.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vanilla", "Forge", "Fabric" }));
        Loader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoaderActionPerformed(evt);
            }
        });

        typelabel.setText("Type filter:");

        typeFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Any", "Release", "Snapshot", "Other" }));
        typeFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeFilterActionPerformed(evt);
            }
        });

        loaderversionlabel.setText("Loader Version:");

        loaderversion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loading" }));
        loaderversion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loaderversionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout play_downloadLayout = new javax.swing.GroupLayout(play_download);
        play_download.setLayout(play_downloadLayout);
        play_downloadLayout.setHorizontalGroup(
            play_downloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(play_downloadLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(play_downloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loaderlabel)
                    .addComponent(Loader, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(play_downloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(versions, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(play_downloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typelabel)
                    .addComponent(typeFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(play_downloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loaderversionlabel)
                    .addComponent(loaderversion, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        play_downloadLayout.setVerticalGroup(
            play_downloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(play_downloadLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(play_downloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(loaderlabel)
                    .addComponent(typelabel)
                    .addComponent(loaderversionlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(play_downloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Loader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loaderversion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(play_download, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(379, Short.MAX_VALUE)
                .addComponent(play_download, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void typeFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeFilterActionPerformed
        VersionsVanilla versionsThread = new VersionsVanilla(versions, typeFilter.getSelectedItem().toString());
        Thread thread = new Thread(versionsThread);
        thread.start();
    }//GEN-LAST:event_typeFilterActionPerformed

    private void LoaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoaderActionPerformed
        Thread thread;
        switch (Loader.getSelectedItem().toString()) {
            case "Fabric":
                loaderversionlabel.setVisible(true);
                loaderversion.setVisible(true);
                typeFilter.setSelectedItem("Release");
                typeFilter.setEnabled(false);
                VersionsFabric versionsThreadFabric = new VersionsFabric(loaderversion);
                thread = new Thread(versionsThreadFabric);
                thread.start();

                break;

            case "Forge":
                loaderversionlabel.setVisible(true);
                loaderversion.setVisible(true);
                typeFilter.setSelectedItem("Release");
                typeFilter.setEnabled(false);
                VersionsForge versionsThreadForge = new VersionsForge(loaderversion, versions.getSelectedItem().toString());
                thread = new Thread(versionsThreadForge);
                thread.start();

                break;

            case "Vanilla":
                loaderversionlabel.setVisible(false);
                loaderversion.setVisible(false);
                typeFilter.setSelectedItem("Any");
                typeFilter.setEnabled(true);

                break;

            default:
                break;
        }
    }//GEN-LAST:event_LoaderActionPerformed

    private void loaderversionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loaderversionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loaderversionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Loader;
    private javax.swing.JPanel instalations_and_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel loaderlabel;
    private javax.swing.JComboBox<String> loaderversion;
    private javax.swing.JLabel loaderversionlabel;
    private javax.swing.JPanel play_download;
    private javax.swing.JComboBox<String> typeFilter;
    private javax.swing.JLabel typelabel;
    private javax.swing.JComboBox<String> versions;
    // End of variables declaration//GEN-END:variables
}
